title: "PowerShellYoungTeam"
description: "PowerShell, Windows administration, dashboards, automation, and occasional weird ideas."
url: "https://powershellyoungteam.github.io"
baseurl: ""
lang: en-GB

markdown: kramdown
remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%b %-d, %Y"

social:
  github: "https://github.com/PowerShellYoungTeam"
  bluesky: "https://bsky.app/profile/poshyoungteam.bsky.social"

header_pages:
  - projects.html
  - about.md
  - archive.html

#header_pages:
 #- about.md   

rss: rss

titles_from_headings:
  strip_title: true
  collections: true

kramdown: {}
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: posts
    values:
        tags: [Other]
